FROM pd/alpinegcc

RUN mkdir -p /opt
ADD jdk-8u201-linux-i586.tar.gz /tmp/
RUN ls -lrt /tmp/ 
RUN mv /tmp/jdk1.8.0_201 /tmp/java.tar.gz
RUN  ls -lrt /tmp/java.tar.gz
RUN gunzip /tmp/java.tar.gz && tar -C /opt -xf /tmp/java.tar && \ ln -s /opt/jdk-8u201 /opt/jdk




